-- DISABLED 2026-09-19: this file's keypress+tile-proximity guesswork
-- ("E pressed near a fence-tagged tile") could not tell a real fence
-- climb apart from opening a gate built from the same fence tile
-- family, causing the dolly/wagon to visibly unequip/re-equip when
-- just opening a gate.
--
-- Superseded by ClimbReEquip.lua, which hooks vanilla's real
-- ISClimbOverFence:perform() directly (the only code path that ever
-- actually performs a climb, covering both short fences and tall
-- walls via the same class) and unequips/re-equips any held
-- container item -- including Base.HCHanddolly / Base.HCToywagon --
-- atomically around the real climb call. That hook only ever fires
-- for a genuine climb, so it has no false-trigger risk by
-- construction and needs no tile-name guessing at all.
--
-- Left in place (inert) rather than deleted so the history/reasoning
-- stays visible; safe to delete outright if preferred.
