-- Vendor_Items.lua
-- Clean category format (B1)

VendorItems = {

    { category = "General" },

    { id = "Base.PopBottle",            name = "Orange Soda",                   price = 20 },
    { id = "Base.WaterBottle",          name = "Water Bottle",                  price = 25 },
    { id = "Base.Crisps",               name = "Bag of Chips - Plain",          price = 15 },
    { id = "Base.Chocolate",            name = "Milk Chocolate Bar",            price = 10 },
    { id = "Base.CandyPackage",         name = "Candy",                         price = 10 },
    { id = "Base.Lighter",              name = "Lighter",                       price = 20 },
    { id = "Base.TinOpener",            name = "Can Opener",                    price = 25 },
    { id = "Base.Key_Blank",            name = "Blank Key",                     price = 10 },
    { id = "Base.Bag_DuffelBag",        name = "Duffelbag <-> Moneybag",        price = 50 },
    { id = "Base.PetrolCan",            name = "Gas Can",                       price = 50 },
    { id = "Base.JerryCan",             name = "Jerry Can",                     price = 50 },
    { id = "Base.SurvivorMultitool",    name = "Survivor-Edition MultiTool",    price = 80 },
    { id = "Base.CannedPotato_Box",     name = "Box of Canned Potato",          price = 50 },
    { id = "Base.HCHanddolly",          name = "Hand Dolly",                    price = 400 },
    { id = "Base.HCToywagon",           name = "Toy Wagon",                     price = 300 },
    { id = "Base.TireRepairKit",        name = "FLukeez - Tire Repair Kit",         price = 150 },
    { id = "Base.SuspensionKit",        name = "FLukeez - Suspension Repair Kit",   price = 150 },
    { id = "Base.BrakeKit",             name = "FLukeez - Brake Repair Kit",        price = 150 },
    { id = "Base.MufflerPatchKit",      name = "FLukeez - Muffler Repair Kit",      price = 150 },
    { id = "Base.BodyRepairKit",        name = "FLukeez - Body Repair Kit",         price = 150 },
    { id = "Base.GasTankRepairKit",     name = "FLukeez - Gas Tank Repair Kit",     price = 150 },
    { id = "Base.BatteryCleanerKit",    name = "FLukeez - Battery Repair Kit",      price = 150 },
    { id = "Base.Superglue",            name = "Super Glue",                    price = 50 },

    {category = "PaintBuckets" },

    { id = "Base.PaintBlue",              name = "Blue Paint",            price = 20 },
    { id = "Base.PaintBlack",             name = "Black Paint",           price = 20 },
    { id = "Base.PaintBrown",             name = "Brown Paint",           price = 20 },
    { id = "Base.PaintCyan",              name = "Cyan Paint",            price = 20 },
    { id = "Base.PaintGrey",              name = "Grey Paint",            price = 20 },
    { id = "Base.PaintGreen",             name = "Green Paint",           price = 20 },
    { id = "Base.PaintLightBlue",         name = "Light Blue Paint",      price = 20 },
    { id = "Base.PaintLightBrown",        name = "Light Brown Paint",     price = 20 },
    { id = "Base.PaintOrange",            name = "Orange Paint",          price = 20 },
    { id = "Base.PaintPink",              name = "Pink Paint",            price = 20 },
    { id = "Base.PaintPurple",            name = "Purple Paint",          price = 20 },
    { id = "Base.PaintTurquoise",         name = "Turquoise Paint",       price = 20 },
    { id = "Base.PaintWhite",             name = "White Paint",           price = 20 },
    { id = "Base.PaintYellow",            name = "Yellow Paint",          price = 20 },

    { category = "Literature" },

    { id = "Base.BookAimingSet",        name = "Aiming Book Box Set",           price = 400 },
    { id = "Base.BookBlacksmithSet",    name = "Blacksmith Book Box Set",       price = 400 },
    { id = "Base.BookButcheringSet",    name = "Butchering Book Box Set",       price = 400 },
    { id = "Base.BookCarpentrySet",     name = "Carpentry Book Box Set",        price = 400 },
    { id = "Base.BookCarvingSet",       name = "Carving Book Box Set",          price = 400 },
    { id = "Base.BookCookingSet",       name = "Cooking Book Box Set",          price = 400 },
    { id = "Base.BookElectricianSet",   name = "Electrician Book Box Set",      price = 400 },
    { id = "Base.BookFarmingSet",       name = "Farming Book Box Set",          price = 400 },
    { id = "Base.BookFirstAidSet",      name = "First Aid Book Box Set",        price = 400 },
    { id = "Base.BookFishingSet",       name = "Fishing Book Box Set",          price = 400 },
    { id = "Base.BookFlintKnappingSet", name = "Knapping Book Box Set",         price = 400 },
    { id = "Base.BookForagingSet",      name = "Foraging Book Box Set",         price = 400 },
    { id = "Base.BookGlassmakingSet",   name = "Glassmaking Book Box Set",      price = 400 },
    { id = "Base.BookHusbandrySet",     name = "Animal Care Book Box Set",      price = 400 },
    { id = "Base.BookLongBladeSet",     name = "Long Blade Book Box Set",       price = 400 },
    { id = "Base.BookMaintenanceSet",   name = "Maintenance Book Box Set",      price = 400 },
    { id = "Base.BookMasonrySet",       name = "Masonry Book Box Set",          price = 400 },
    { id = "Base.BookMechanicsSet",     name = "Mechanics Book Box Set",        price = 400 },
    { id = "Base.BookMetalWeldingSet",  name = "Welding Book Box Set",          price = 400 },
    { id = "Base.BookPotterySet",       name = "Pottery Book Box Set",          price = 400 },
    { id = "Base.BookReloadingSet",     name = "Reloading Book Box Set",        price = 400 },
    { id = "Base.BookTailoringSet",     name = "Tailoring Book Box Set",        price = 400 },
    { id = "Base.BookTrackingSet",      name = "Tracking Book Box Set",         price = 400 },
    { id = "Base.BookTrappingSet",      name = "Trapping Book Box Set",         price = 400 },
    { id = "Base.MechanicMag1",         name = "Magazine: Laines Standard Auto Manual",     price = 100 },
    { id = "Base.MechanicMag2",         name = "Magazine: Laines Commercial Auto Manual",   price = 100 },
    { id = "Base.MechanicMag3",         name = "Magazine: Laines Performance Auto Manual",  price = 100 },

    { category = "Generators" },

    { id = "Base.ElectronicsMag4",      name = "Magazine: How to Use Generators", price = 150 },
    { id = "Base.Generator_Yellow",     name = "Generator - Premium",           price = 600 },
    { id = "Base.Generator",            name = "Generator - Regular",           price = 500 },
    { id = "Base.Generator_Blue",       name = "Generator - ValueTech",         price = 350 },

    { category = "Medical" },

    { id = "Base.AdhesiveBandageBox",   name = "Box of Adhesive Bandages",      price = 25 },
    { id = "Base.BandageBox",           name = "Box of Bandages",               price = 40 },
    { id = "Base.AntibioticsBox",       name = "Box of Antibiotics",            price = 75 },
    { id = "Base.CottonBallsBox",       name = "Box of Cotton Balls",           price = 75 },
    { id = "Base.SyringeWithCure",      name = "Syringe Containing The Cure",   price = 1000 },

    { category = "Melee" },

    { id = "Base.HuntingKnife",         name = "Hunting Knife",                 price = 150 },
    { id = "Base.HandAxe",              name = "Hatchet",                       price = 200 },
    { id = "Base.Axe",                  name = "Axe",                           price = 300 },
    { id = "Base.WoodAxe",              name = "Wood Axe",                      price = 300 },
    { id = "Base.Katana",               name = "Katana",                        price = 300 },
    { id = "Base.Machete",              name = "Machete",                       price = 250 },
    { id = "Base.PickAxe",              name = "PickAxe",                       price = 200 },
    { id = "Base.Crowbar",              name = "Crowbar",                       price = 200 },
    { id = "Base.Sledgehammer",         name = "Classic SledgeHammer",          price = 300 },
    { id = "Base.Sledgehammer2",        name = "Polished SledgeHammer",         price = 300 },
    { id = "Base.BastardSword",         name = "Bastard Sword",                 price = 600 },
    { id = "Base.cfcombataxe",          name = "*Carbon Fibre Combat Axe*",     price = 800 },
    { id = "Base.cflongreachaxe",       name = "*Carbon Fibre Long Reach Axe*", price = 800 },

    { category = "Guns" },

    { id = "Base.Pistol",               name = "9mm Pistol",                    price = 200 },
    { id = "Base.DoubleBarrelShotgun",  name = "Double Barrel Shotgun",         price = 350 },

    { category = "Ammunition" },

    { id = "Base.Bullets9mmBox",        name = "Box of 9x19mm Rounds",          price = 50 },
    { id = "Base.ShotgunShellsBox",     name = "Box of Shotgun Shells",         price = 50 },
    { id = "Base.Bullets38Box",         name = "Box of .38 Special Rounds",     price = 50 },
    { id = "Base.Bullets44Box",         name = "Box of .44 Magnum Rounds",      price = 50 },
    { id = "Base.Bullets45Box",         name = "Box of .45 Auto Rounds",        price = 50 },
    { id = "Base.223Box",               name = "Box of .223 Rounds",            price = 50 },
    { id = "Base.308Box",               name = "Box of .308 Rounds",            price = 50 },
    { id = "Base.3030Box",              name = "Box of .30-30 Rounds",          price = 50 },
    { id = "Base.556Box",               name = "Box of 5.56mm Rounds",          price = 50 },
    { id = "Base.Bullets357Box",        name = "Box of .357 Magnum Rounds",     price = 50 },
    
}